name: Extract ZIP File

on:
  push:
    paths:
      - '*.zip' # Trigger the workflow when a ZIP file is pushed

jobs:
  extract_zip:
    runs-on: ubuntu-22.04 # Specify the exact version to avoid compatibility issues

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install unzip (if not already available)
      - name: Install unzip
        run: sudo apt-get install unzip

      # Step 3: Unzip the uploaded ZIP file
      - name: Unzip file
        run: |
          for file in *.zip; do
            unzip "$file" -d extracted_files
          done

      # Step 4: Commit and push changes
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Extracted ZIP file contents"
          branch: main # Replace with the branch you are working on
